[package]
name = "reqsnitch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.9.1"
etherparse = "0.10.1"
hexdump = "0.1.1"
